
name: dev
services:
  dev-app:
    container_name: dev-app
    depends_on:
      dev-mysql:
        condition: service_started
        required: true
    environment:
      ENVIRONMENT: development
    image: dev-app:0.1
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "89"
        protocol: tcp
    volumes:
      - type: volume
        source: app
        target: /var/www/html
        volume: {}
  dev-mysql:
    container_name: dev-mysql
    image: dev-mysql:0.1
    logging:
      options:
        max-file: "3"
        max-size: 10m
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3306
        published: "3306"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
        volume: {}
      - type: bind
        source: C:\Users\chris\OneDrive\IT\PartageonsLaForet\github_plf\plf\docker\dev\mysql
        target: /docker-entrypoint-initdb.d
        bind:
          create_host_path: true
  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    networks:
      default: null
    ports:
      - mode: ingress
        target: 1080
        published: "1080"
        protocol: tcp
      - mode: ingress
        target: 1025
        published: "1025"
        protocol: tcp
    restart: on-failure
networks:
  default:
    name: dev_default
volumes:
  app:
    name: dev_app
  mysql:
    name: dev_mysql
