apiVersion: apps/v1
kind: Deployment
metadata:
  name: plf-dev-mailcatcher
spec:
  selector:
    matchLabels:
      app: plf-dev-mailcatcher
  template:
    metadata:
      labels:
        app: plf-dev-mailcatcher
    spec:
      containers:
        - image: dockage/mailcatcher:0.9.0
          name: plf-dev-mailcatcher
          resources: 
          imagePullPolicy: Never
          ports:
            - containerPort: 1080
              hostPort: 1080
              protocol: TCP
            - containerPort: 1025
              hostPort: 1025
              protocol: TCP


