apiVersion: apps/v1
kind: Deployment
metadata:
  name: plf-dev-pgadmin
  namespace: plf-dev
spec:
  selector:
    matchLabels:
      app: plf-dev-pgadmin
  template:
    metadata:
      labels:
        app: plf-dev-pgadmin
    spec:
      containers:
        - image: plf-dev-pgadmin:8.4
          name: plf-dev-pgadmin
          resources:
          imagePullPolicy: Never
          env:
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plf-dev-secrets
                  key: postgresql_password
            - name: PGADMIN_DEFAULT_EMAIL
              value: "christian.lurkin@hotmail.com"
            - name: PGADMIN_DISABLE_POSTFIX
              value: ""
          ports:
            - containerPort: 80
              name: pgadmin-port

