apiVersion: v1
kind: PersistentVolume
metadata:
  name: plf-dev-mysql-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"