apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plf-dev-postgresql-pvc
  namespace: plf-dev
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi