version: '3.9'
volumes:
  postgres-data: 
services:
    postgres:
        build: 
          dockerfile: docker/Dockerfile-postgres
        restart: always
        env_file:
          - .env
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          #- ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    
    php:
      image: php:8.2-apache
      ports:
        - 89:80
      volumes:
        - ./desktop:/var/www/html/
        - ./.env:/var/www/.env