apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dev
spec:
  selector:
    matchLabels:
      app: mysql-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dev
    spec:
      containers:
        - image: dev-mysql:1.0
          name: dev-mysql
          imagePullPolicy: Never
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

