apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\chris\AppData\Local\Microsoft\WinGet\Links\kompose.exe -f .\docker-compose-dev.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: dev-app
  name: dev-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\chris\AppData\Local\Microsoft\WinGet\Links\kompose.exe -f .\docker-compose-dev.yml convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/dev-default: "true"
        io.kompose.service: dev-app
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: development
          image: dev-app:0.1
          name: dev-app
          ports:
            - containerPort: 80
              hostPort: 89
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: app
      restartPolicy: Always
      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: app
status: {}
