apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\chris\AppData\Local\Microsoft\WinGet\Links\kompose.exe -f .\docker-compose-dev.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/dev-default: "true"
    io.kompose.service: mailcatcher
  name: mailcatcher
spec:
  containers:
    - image: dockage/mailcatcher:0.9.0
      name: mailcatcher
      ports:
        - containerPort: 1080
          hostPort: 1080
          protocol: TCP
        - containerPort: 1025
          hostPort: 1025
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
