apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\chris\AppData\Local\Microsoft\WinGet\Links\kompose.exe -f .\docker-compose-dev.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mailcatcher
  name: mailcatcher
spec:
  ports:
    - name: "1080"
      port: 1080
      targetPort: 1080
    - name: "1025"
      port: 1025
      targetPort: 1025
  selector:
    io.kompose.service: mailcatcher
status:
  loadBalancer: {}
