apiVersion: v1
kind: PersistentVolume
metadata:
  name: plf-dev-pg-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
