apiVersion: apps/v1
kind: Deployment
metadata:
  name: plf-dev-phpmyadmin
spec:
  selector:
    matchLabels:
      app: plf-dev-phpmyadmin
  template:
    metadata:
      labels:
        app: plf-dev-phpmyadmin
    spec:
      containers:
        - image: phpmyadmin:latest
          name: plf-dev-phpmyadmin
          resources:
          imagePullPolicy: Never
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: plf-dev-configmap
                  key: MYSQL_HOST
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plf-dev-secrets
                  key: mysql_root_password
          ports:
            - containerPort: 80

