apiVersion: v1
kind: ConfigMap
metadata:
  name: plf-dev-configmap
data:
  MYSQL_HOST: plf-dev-mysql-ip
  MYSQL_DATABASE: plf_dev
  MYSQL_USER: plf
  # mailcatcher
  mail_Host: "plf-dev-mailcatcher-ip"
  mail_Port: "1025"
  mail_Username: "christian.lurkin@gmail.com"
  mail_Password: ""
  mail_SMTPAuth: ""
  mail_SMTPSecure: ""
